### ISSUE TITLE
ticketkapat Komutu Çalışmıyor

### ISSUE THREAD

**Issue by ghost** [Arpelo/discord-turkce-ticket-system#1]
Ticket Kapat Komutu Kullandıktan sonra -kapat yazıyorum fakat kapanmıyor.Kodun düzenlenmesi lazım.

@Arpelo

**Comment by hakanyigitertemur** [comment]
kodda herhangi bir sorun yok, ticket açıldıktan sonra kanal adının değiştirilmesi durumunda "-kapat" çalışmıyor sadece :)

**Comment by ghost** [comment]
kanal adı değişmedi

**Comment by ghost** [comment]
fakat ben komutları ayrı dosyalar haline getirdim bi etkisi varmı?

**Comment by ghost** [comment]
@Arpelo

**Comment by ghost** [comment]
@Arpelo bakarmısın?

**Comment by hakanyigitertemur** [comment]
ne demek istediğini anlamadım?
kodlarda herhangi bir problem bulunmuyor

**Comment by hakanyigitertemur** [comment]
eğer problemin devam ediyorsa Arpelo#5902 iletişime geçebilirsin iyi günler :wave:

**Comment by EmreTurkmen-Hub** [comment]
Merhaba bu dosyayı nereye atıyoruz

**Comment by ghost** [comment]
@mr38emre

Kod zaten tek dosya onuda istediğin yere atıp çalıştırman lazım.

DC: RedS#6100
