### ISSUE TITLE
ticketkapat Komutu Çalışmıyor

### ISSUE THREAD

**Issue by MuratGokhanAsn** [Arpelo/discord-turkce-ticket-system#2]
Ticket Kapat Komutu Kullandıktan sonra -kapat yazıyorum fakat kapanmıyor.Kodun düzenlenmesi lazım.

**Comment by hakanyigitertemur** [comment]
Evet,dostum farkındayım kodu düzenlemen gerekiyor bunu başarabilirsin 🙃
